### ISSUE TITLE
NFS listing works very slow if active io is on

### ISSUE THREAD

**Issue by bosher** [Nexenta/edgefs#284]
### Summary 
NFS ls takes minutes if heavy io is on.

### Steps to reproduce the behavior
Run vdb job on 6-node cluster, write 1G files by 16 threads.

ls command for a 3000+ files takes more then 3 minutes

### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
I'm surprised why Version Manifests isn't cached in libccow UCACHE... 3000 files are just 20KB or so

**Comment by dyusupov** [comment]
UCACHE and CMCACHE has a bug that was addressed in the recent builds. Closing this issue for now.
