### ISSUE TITLE
Enable ISGW mdonly/vmonly flags on the tenent/bucket replication path

### ISSUE THREAD

**Issue by bosher** [Nexenta/edgefs#285]
### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
Fixed in the latest.
