### ISSUE TITLE
efscli does not list clusters, tenants

### ISSUE THREAD

**Issue by NullOranje** [Nexenta/edgefs#298]
### Summary 
Clusters/tenants created by either efscli or the UI are not listed when executing `efscli cluster list` or `efscli tenant list Hawaii`.  The clusters do appear when running `neadm cluster list` or `neadm tenant list`

### Steps to reproduce the behavior
1. Create a new cluster: `efscli cluster create -r 3 -c 3:1:xor Hawaii`
2. Try to list the cluster `efscli cluster list`
3. Verify cluster was created: `neadm cluster list`

### Expected behavior
Display newly created cluster.

### Actual behavior
Results are not displayed.
```
# efscli cluster list 
# echo $?
0
# neadm cluster list -x
CLUSTER EC_ON EC_MODE REPCNT 
Hawaii  1     3:1:xor 3
```

### EdgeFS version
1.2.19

### Deployment type

- [x] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [x] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster
Kubernetes 1.14.3 deployed via Kubespray

- [x] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
gist with the output of "CCOW_LOG_LEVEL=0 efscli cluster list" might help us to get a better idea on what is going on.

**Comment by NullOranje** [comment]
`CCOW_LOG_LEVEL=0 efscli cluster list` also produces no output

**Comment by dyusupov** [comment]
sorry, it will dump to var/log/ccow.log. Or to get it to dump on the console try this: "CCOW_LOG_LEVEL=0 CCOW_LOG_STDOUT=1 efscli cluster list"

**Comment by NullOranje** [comment]
That makes a difference.

https://gist.github.com/NullOranje/2fe3142bc0ed8fd3ab07ea727a499a4d

**Comment by dyusupov** [comment]
> That makes a difference.
> 
> https://gist.github.com/NullOranje/2fe3142bc0ed8fd3ab07ea727a499a4d

This looks correct to me. Could you also upload the result of: "CCOW_LOG_LEVEL=0 CCOW_LOG_STDOUT=1 efscli tenant list Hawaii" ?

**Comment by NullOranje** [comment]
Of course: https://gist.github.com/NullOranje/f19169be6f97b7697acd51bc1b83369c

**Comment by dyusupov** [comment]
I see no tenants created, could you try these commands and see if it outputs tenants correctly?

**Comment by NullOranje** [comment]
It lists it here, but the other tenant shows up in `neadm`

```
root@rook-edgefs-mgr-595547bb4-qmbw9:/opt/nedge# efscli tenant create Hawaii/test
root@rook-edgefs-mgr-595547bb4-qmbw9:/opt/nedge# efscli tenant list Hawaii
test
root@rook-edgefs-mgr-595547bb4-qmbw9:/opt/nedge# neadm tenant list Hawaii
CLUSTER TENANT 
Hawaii  Cola   
Hawaii  test   
```

**Comment by dyusupov** [comment]
Could you delete mgr pod (let it restart and thus clear REST API memory cache). Just want to locate the component with the problem.

**Comment by NullOranje** [comment]
Deleting the pod seems to yield the same result:
```
root@rook-edgefs-mgr-595547bb4-gg5rj:/opt/nedge# efscli tenant list Hawaii
test
root@rook-edgefs-mgr-595547bb4-gg5rj:/opt/nedge# neadm tenant list Hawaii
CLUSTER TENANT 
Hawaii  Cola   
Hawaii  test   
```

**Comment by dyusupov** [comment]
In your configuration of cluster you have "-c 3:1:xor" that implies 4 devices (3+1) but in the cluster you only have 3. Could you create new cluster with "-c 2:1:xor" or without EC at all? Please be aware of https://github.com/Nexenta/edgefs/issues/197

**Comment by NullOranje** [comment]
```
root@rook-edgefs-mgr-595547bb4-gg5rj:/opt/nedge# efscli cluster create NewYork
root@rook-edgefs-mgr-595547bb4-gg5rj:/opt/nedge# efscli cluster list
root@rook-edgefs-mgr-595547bb4-gg5rj:/opt/nedge# neadm cluster list -x
CLUSTER EC_ON EC_MODE REPCNT 
NewYork 0     6:2:rs  3      
Hawaii  1     3:1:xor 3 
root@rook-edgefs-mgr-595547bb4-gg5rj:/opt/nedge# efscli tenant create NewYork/test1
root@rook-edgefs-mgr-595547bb4-gg5rj:/opt/nedge# efscli tenant list NewYork
test1
```

I can see the tenant, but the cluster still doesn't show.

**Comment by dyusupov** [comment]
ok, what versions you are running?

**Comment by NullOranje** [comment]
```
kubectl -n rook-edgefs describe pods | grep "Image:" | sort | uniq
    Image:          edgefs/edgefs-ui:1.2.19
    Image:         edgefs/edgefs-restapi:1.2.19
    Image:         edgefs/edgefs:1.2.19
```

**Comment by dyusupov** [comment]
Lets try to upgrade to 1.2.21. "kubectl edit Cluster -n rook-edgefs" and change version..

**Comment by NullOranje** [comment]
Updated to 1.2.21.  Same results

```
root@rook-edgefs-mgr-5dcc7f5bdc-phfdr:/opt/nedge# efscli cluster list
root@rook-edgefs-mgr-5dcc7f5bdc-phfdr:/opt/nedge# neadm cluster list -x
CLUSTER EC_ON EC_MODE REPCNT 
Hawaii  1     3:1:xor 3      
NewYork 0     6:2:rs  3 
```
https://gist.github.com/NullOranje/626e8ababc6dcc6e476440d9242cc45e

**Comment by dyusupov** [comment]
Ok. I want also double check your FlexHash configuration. Could you please do "efscli system fhtable rediscover" then "efscli system fhtable print" and then "efscli system fhtable set". Once re-set like this, try again.

**Comment by NullOranje** [comment]
```
root@rook-edgefs-mgr-5dcc7f5bdc-phfdr:/opt/nedge# efscli system fhtable rediscover
Do you really want to change cluster wide checkpoint at this time? [y/n]: y
Sent message to daemon: FH_CPUPD.SIGUSR2
Successfully re-generated FlexHash table
root@rook-edgefs-mgr-5dcc7f5bdc-phfdr:/opt/nedge# efscli system fhtable print
leader 0
failure_domain 1
zonecount 0
genid 1563562631559989
servercount 3
vdevcount 3
pid 22063
from_checkpoint 1
numrows 8
root@rook-edgefs-mgr-5dcc7f5bdc-phfdr:/opt/nedge# efscli system fhtable set
Please confirm initial configuration? [y/n]: y
Sent message to daemon: FH_CPSET.1563562631559989
Successfully set FlexHash table to GenID=1563562631559989
root@rook-edgefs-mgr-5dcc7f5bdc-phfdr:/opt/nedge# efscli cluster list
root@rook-edgefs-mgr-5dcc7f5bdc-phfdr:/opt/nedge# neadm cluster list -x
CLUSTER EC_ON EC_MODE REPCNT 
Hawaii  1     3:1:xor 3      
NewYork 0     6:2:rs  3    
```

**Comment by dyusupov** [comment]
It sounds like a real bug the cause for each is not known. Before we leave it at that, lets please try to do full cluster re-creation following this procedure:

1. kubectl delete -f cluster.yaml
2. on each host: rm -rf /var/lib/edgefs
3. on each host for each device: wipefs -a /dev/NAME; dd if=/dev/zero of=/dev/NAME bs=1M count=10
4. kubect create -f cluster.yaml
5. init again, but use efscli only

**Comment by NullOranje** [comment]
Rebuilt cluster exhibits the same issue:
```
Welcome to EdgeFS Mgmt Toolbox.
Hint: type neadm or efscli to begin

root@rook-edgefs-mgr-595547bb4-qt895:/opt/nedge# efscli cluster create Hawaii
root@rook-edgefs-mgr-595547bb4-qt895:/opt/nedge# efscli cluster list
root@rook-edgefs-mgr-595547bb4-qt895:/opt/nedge# efscli tenant create Hawaii/test1 
root@rook-edgefs-mgr-595547bb4-qt895:/opt/nedge# efscli tenant list Hawaii
test1
```

**Comment by dyusupov** [comment]
I wonder if you could try to rebuild with 2 disks per host config? Just to rule out a possibility of a bug in FlexHash.

**Comment by NullOranje** [comment]
Sure.  Still having issues listing cluster, and now the tenant isn't listing again.
```
root@rook-edgefs-mgr-595547bb4-vhnlf:/opt/nedge# efscli system status -v1
ServerID 315AB696AB0FAAEFDE5CF115BD8415E6 csp-north-test-server2:rook-edgefs-target-1-0 ONLINE
  VDEVID 62391D95470AE1213AB2253EFF508A43 scsi-36000c2902c0ec7b5146031394bb4c928 ONLINE
  VDEVID 2BF953EDA6E408B6E8F9A1710115BC12 scsi-36000c29ed06b3c11aab59338673b61d9 ONLINE
ServerID 9CBCAFDE3F4C93EE64CE60BA85F16AD7 csp-north-test-server3:rook-edgefs-target-2-0 ONLINE
  VDEVID 17046D6D471CE8029CB23200A3402E1F scsi-36000c29cfd387f6be38c00e0e7935859 ONLINE
  VDEVID 6B0E8EFE253C88AB4304597BF169FE92 scsi-36000c29f0b3a0c2dd3bbb40dc97b9bd4 ONLINE
ServerID 590F3B1871DD6AC66F6B7B906ECA4158 csp-north-test-server1:rook-edgefs-target-0-0 ONLINE
  VDEVID A620C7C5F3DC147D3BEFCC0BD7A7B98C scsi-36000c299b857d8a561374b81b56adc4f ONLINE
  VDEVID 6B655CC4B9C172D05C56E8F7D816AB92 scsi-36000c296e8b5ead27902abdf13bcacc0 ONLINE
root@rook-edgefs-mgr-595547bb4-vhnlf:/opt/nedge# efscli cluster create Hawaii
root@rook-edgefs-mgr-595547bb4-vhnlf:/opt/nedge# efscli cluster list Hawaii
root@rook-edgefs-mgr-595547bb4-vhnlf:/opt/nedge# neadm cluster list Hawaii -x
CLUSTER EC_ON EC_MODE REPCNT 
Hawaii  0     6:2:rs  3      
root@rook-edgefs-mgr-595547bb4-vhnlf:/opt/nedge# efscli tenant create Hawaii/Cola
root@rook-edgefs-mgr-595547bb4-vhnlf:/opt/nedge# efscli tenant list Hawaii
root@rook-edgefs-mgr-595547bb4-vhnlf:/opt/nedge# efscli tenant create Hawaii/Tenant2
root@rook-edgefs-mgr-595547bb4-vhnlf:/opt/nedge# efscli tenant list Hawaii
root@rook-edgefs-mgr-595547bb4-vhnlf:/opt/nedge# neadm tenant list
CLUSTER TENANT  
Hawaii  Cola    
Hawaii  Tenant2 
```

**Comment by dyusupov** [comment]
Reproduced in my lab. We will be looking into this issue next week. Thanks for all the help!

**Comment by NullOranje** [comment]
Thanks for your quick turnaround  I'm having a few more issues, but I think they're related to #302, so I'll test more before reporting.

**Comment by dyusupov** [comment]
edgefs/edgefs:1.2.25 uploaded - please verify if issue is fixed. If not, please reopen it or create new issue. Thank you

**Comment by NullOranje** [comment]
I no longer see this behavior running 1.2.25.  This appears to be resolved.
