### ISSUE TITLE
It is impossible to setup  ACLs through ccowhttpd 

### ISSUE THREAD

**Issue by bosher** [Nexenta/edgefs#300]
### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
Fixed in https://github.com/Nexenta/edgefs/pull/325
