### ISSUE TITLE
corosync configuration in a non-kubernetes environment

### ISSUE THREAD

**Issue by SergeyKaydalov** [Nexenta/edgefs#322]
### Summary 
corosync configuration isn't created without running in k8s environment.

The corosync-pod-watcher creates/updates a corosync configuration file since recently. However, the corosync-pod-watcher is able to run only in the k8s container. 

### Expected behavior
As per https://github.com/Nexenta/edgefs/wiki/Development-Guide, the `efscli config node -i eth0` is used to create node configuration. It must be capable to create corosync.conf in a non-kubernetes environment.

### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
Fixed in https://github.com/Nexenta/edgefs/pull/331
