### ISSUE TITLE
s3x support for authentication and acls is broken

### ISSUE THREAD

**Issue by bosher** [Nexenta/edgefs#324]
### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
fixed in https://github.com/Nexenta/edgefs/pull/329
