### ISSUE TITLE
Space Reclaim issue with large sequentially written objects

### ISSUE THREAD

**Issue by SergeyKaydalov** [Nexenta/edgefs#344]
### Summary 
It seems the Space Reclaim isn't working or is inefficient for object written sequentially. 
Their put construct is similar to how a block device flushes its data:

while (!eof) {
   read(N); //Get N source data blocks
   ccow_put_cont(N); // Put N blocks to the EdgeFS store
   ccow_finalize(); // Finalize the stream, this will create new object version
}

The source of a problem is under investigation.

### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
As a result of triaging today, the issue can affect only files or LUNs that are being active for some time > 10min and then suddenly went idle forever. S3/S3X objects not affected.

The theory is that when we create quarantined versions within negotiating groups, we lacking coordination on so-called "stable version" purge. As a result, we may end up with 2+ versions while ccow-number-of-versions is set to 1.
