### ISSUE TITLE
S3x kvget request returns wrong value if the requested key not available 

### ISSUE THREAD

**Issue by bosher** [Nexenta/edgefs#360]
### Summary 

S3x kvget request should return an error if the requested key not available

### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
fix integrated
