### ISSUE TITLE
S3 Auth with Access/Secret key

### ISSUE THREAD

**Issue by PhanQ** [Nexenta/edgefs#380]
Hello,
I saw an option for S3 Object Auth-Type with `key_secret` in dashboard, but can't configure Access/Secret key for it. Anyway to configure it via dashboard or efscli command? Thanks in advanced.

**Comment by bosher** [comment]
Please try to create a new user:

 efscli user create <cluster>/<tenant> <username> <password> [admin]

The command will return key/secret pair.

The admin flag is optional and creates the administrator user in case when s3 ACLs are used.

**Comment by PhanQ** [comment]
Thank you. I can create user now with returned key/secret pair.
My question now is how can we assign user to a service object, so that we can have different credentials for each service object. Could you refer to some `efscli` cheat sheet to do that?
I also want to configure credential for s3 object in yaml file when we create it in Kubernetes cluster with Rook-EdgeFS operator. Can we do that?
Thank you!

**Comment by bosher** [comment]
The s3 ACLs could be configured on bucket level using s3 protocol:

https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html

E.g. you create the administrator user and use some s3 tool to create/change the ACLs.

Here are some examples with s3cmd:

s3cmd --acl-private  setacl s3://bk1
s3cmd --acl-grant=read:user1  setacl s3://bk1
s3cmd --acl-public  setacl s3://bk1
s3cmd --acl-grant=read:* setacl s3://bk1  - all users
s3cmd --acl-grant=read_acp:*  setacl s3://bk1 - all users

The s3cmd configuration should include  key/secret for admin user.

**Comment by PhanQ** [comment]
Thank @bosher 

I tried with `s3cmd` to create and modify ACL, but looks like it doesn't appy the changes. It always 
setting as ` *anon*: FULL_CONTROL`. 

# s3cmd --acl-private setacl s3://bucket
s3://bucket5/: ACL set to Private
# s3cmd --acl-grant=read:* setacl s3://bucket
s3://bucket5/: ACL updated
# s3cmd info s3://bucket5/img.jpg|grep -i acl
   ACL:       *anon*: FULL_CONTROL

**Comment by bosher** [comment]
Could you please do 'efscli service show [service_name]' and post the output?

**Comment by PhanQ** [comment]
```# efscli service show objects
X-Service-Name: objects
X-Service-Type: s3
X-Description: S3 Object
X-Region: -
X-Servers: -
X-Need-MD5: true
X-List-Max-Size: 1000
X-List-Cache: true
X-HTTP-Port: 9982
X-HTTPS-Port: 9443
X-HTTPS-Key: -
X-HTTPS-Cert: -
X-Ciphers: -
X-Default-Tenant: -
X-Default-Owner: -
X-Trust-Proxy: true
X-Access-Log: false
X-Number-Of-Versions: 1
X-ContainerIPv6-6A4BA474F9F1B5FFBC6604C72D2B543F: ::ffff:ffff:-7187:e90a
X-Container-Hostname-6A4BA474F9F1B5FFBC6604C72D2B543F: x.x.x.x
X-ContainerId-6A4BA474F9F1B5FFBC6604C72D2B543F: rook-edgefs-s3-objects-57ddbd87b5-7wkbq
X-Status: enabled
X-ContainerIPv6-D4856920ED606933F227E37FC2EE3C87: ::ffff:ffff:-54a9:e90a
X-Container-Hostname-D4856920ED606933F227E37FC2EE3C87: x.x.x.x
X-ContainerId-D4856920ED606933F227E37FC2EE3C87: rook-edgefs-s3-objects-786d767bb9-sqkdd
X-Auth-Type: key_secret
X-ACL-On: true
X-List-All-Buckets: false
[
  cltest/test
]
```

**Comment by PhanQ** [comment]
@bosher Have you found any wrong?  I tried enable `X-ACL-On` to true but no luck.

**Comment by bosher** [comment]
The configuration looks correct. Have you tried to restart the service:

kubectl scale deploy rook-edgefs-s3-objects --replicas=0
kubectl scale deploy rook-edgefs-s3-objects --replicas=1

**Comment by PhanQ** [comment]
It works after service restart. Thank @bosher.
