### ISSUE TITLE
Expunge command does not remove object from the bucket

### ISSUE THREAD

**Issue by bosher** [Nexenta/edgefs#387]
### Summary 

Expunge command does not remove object from the bucket

### Steps to reproduce the behavior

efscli object create cluster/bucket/object
efscli object delete cluster/bucket/object -e
efscli object list  cluster/bucket

### Actual behavior

the object still in the bucket after a minute

### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
fixed in the master
