### ISSUE TITLE
Enabled transparency - NFS/S3 causing empty root directory listing being incorrect

### ISSUE THREAD

**Issue by n3m8tz** [Nexenta/edgefs#396]

**Comment by bosher** [comment]
[root@m1 edgefs-segmented-config]# mkdir /mnt/test
[root@m1 edgefs-segmented-config]# mount -t nfs -o tcp,vers=3,actimeo=1 10.110.172.192:/hpwren/test /mnt/test
[root@m1 edgefs-segmented-config]# ls -l /mnt/test
ls: reading directory /mnt/test: Too many levels of symbolic links
total 0

**Comment by bosher** [comment]
root@rook-edgefs-mgr-7499545d9c-zlhnw:/opt/nedge# exit
exit
[root@m1 edgefs-segmented-config]# tool ucsc
Manager: rook-edgefs-ucsc rook-edgefs-mgr-7fb76cdd49-s78rw
Defaulting container name to rook-edgefs-mgr.
Use 'kubectl describe pod/rook-edgefs-mgr-7fb76cdd49-s78rw -n rook-edgefs-ucsc' to see all of the containers in this pod.

Welcome to EdgeFS Mgmt Toolbox.
Hint: type neadm or efscli to begin

root@rook-edgefs-mgr-7fb76cdd49-s78rw:/opt/nedge# efscli service show hpwren-nfs
X-Service-Name: hpwren-nfs
X-Service-Type: nfs
X-Description: NFS Server
X-Servers: -
X-Auth-Type: disabled
X-MH-ImmDir: 1
X-Status: enabled
X-ContainerIPv6-C8D864A30DAB53768892C7C69E522990: -
X-Container-Hostname-C8D864A30DAB53768892C7C69E522990: fiona-100g.ucsc.edu
X-ContainerId-C8D864A30DAB53768892C7C69E522990: rook-edgefs-nfs-hpwren-nfs-85fd557c48-cp4x4
[
  2,hpwren/test@hpwren/hpwren/test

**Comment by bosher** [comment]
The hpwren/hpwren/test bucket was created with transparency flag.

**Comment by bosher** [comment]
The same problem: 

[root@m1 tests]# ls -la /mnt/bk3/.objects/
ls: reading directory /mnt/bk3/.objects/: Too many levels of symbolic links
total 5
dr-xr-xr-x 2 root root 1008 Nov 21 17:07 .
drwxr-xr-x 3 root root 2016 Nov 21 16:59 ..
dr-xr-xr-x 1 root root 1500 Nov 21 17:01 dir1
dr-xr-xr-x 1 root root 1500 Nov 21 17:01 dir1
dr-xr-xr-x 1 root root 1500 Nov 21 17:01 dir1
dr-xr-xr-x 1 root root 1500 Nov 21 17:01 dir1
