### ISSUE TITLE
Object listing through NFS never returns

### ISSUE THREAD

**Issue by bosher** [Nexenta/edgefs#435]
### Summary 

1. Create transparancy enabled bucket

2. Create deep and big object tree in the bucket 

3. Create NFS service for the bucket

4. Do root ls for the objects. E.g:

ls -l /mnt/bucket/.objects

The lust command never returns.

### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
fix now integrated
