### ISSUE TITLE
Roll back changes made in #423

### ISSUE THREAD

**Issue by rajeshbha** [Nexenta/edgefs#437]
### Summary 
Roll back changes made in #423 
Reintroduce "-s" flag in edges-start.sh nfs

### Deployment type

- [* ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ *] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
fix now integrated
