### ISSUE TITLE
Only one instance is created for bucket chunk manifest if sync_put equal to 1. 

### ISSUE THREAD

**Issue by bosher** [Nexenta/edgefs#442]
### Summary 

Only one instance is created for bucket chunk manifest if sync_put equal to 1.
We should ignore sync_put for bucket updates to avoid possible data loss for the bucket.

### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
fix now integrated.
