### ISSUE TITLE
Unable to mount nfs shares,  doesnt appear nfs is started.

### ISSUE THREAD

**Issue by treyormsbee-interop** [Nexenta/edgefs#514]
### Summary 

Im am atempting to launch a vm based cluster of 3 nodes.  After setup is complete I launch the nfs docker image to serve out the nfs share.  But no nfs client appears to be able to see or be able to mount the share.

[iedgefstest02 ~]$ showmount -e x.x.x.x
clnt_create: RPC: Program not registered
[edgefstest02 ~]$ rpcinfo -p x.x.x.x
   program vers proto   port  service
    100000    4   tcp    111  portmapper
    100000    3   tcp    111  portmapper
    100000    2   tcp    111  portmapper
    100000    4   udp    111  portmapper
    100000    3   udp    111  portmapper
    100000    2   udp    111  portmapper

Maybe I am missing soemthing but should the nfs ports be exposed on the docker container for this to work?  

CONTAINER ID                                                       IMAGE                  COMMAND                                    CREATED             STATUS              PORTS               NAMES
b63c2bb1bbfed915c0433808089e2a55066708b23d209e59a5d1d562a40e5f6f   edgefs/edgefs:latest   "/opt/nedge/sbin/edgefs-start.sh nfs"      6 minutes ago       Up 6 minutes                            affectionate_dubinsky

### Steps to reproduce the behavior

Follow deployment guide,  to the point of launching nfs docker container,  then attempt to mount the share.

### Expected behavior

Should be ale to mount the nfs share.

### Actual behavior

unable to mount nfs share.

### EdgeFS version

1.2.167

### Deployment type

Docker with 3 nodes,

Select deployment resource policy. 
-->
- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ x ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

No k8s just centos 7 vm's

**Comment by dyusupov** [comment]
have you tried to enable host networking? It seems that server isn't registered with RPC.

**Comment by treyormsbee-interop** [comment]
That appears to have been the problem,  could the documentation be updated to show that --net=host should be used with the docker nfs deployment? 

http://edgefs.io/docs/Docker-NFS-service-with-static-exports.html

Thanks,
Trey

**Comment by dyusupov** [comment]
Yes, please feel free to edit wiki pages. Thanks - closing the issue for now.
