### ISSUE TITLE
New cluster some disks startup as faulted, unable to VDEV -13

### ISSUE THREAD

**Issue by treyormsbee-interop** [Nexenta/edgefs#515]
Summary 

New cluster deployment with 3 vm guests and 3 100GB disks each for edgefs storage.  Only one disk successfully partitions on initial start. The other 2 show faulted.

### Steps to reproduce the behavior

deploy new cluster 3 node cluster with vmware guests and 3 disks each, run wipefs on each 3 disks,  run config on each node,  then target on each node. After a while all 3 nodes will come online with only one good disk each.  

### Expected behavior

online with three online disks

### Actual behavior

2 disks do not partition.

### EdgeFS version

1.2.167

### Deployment type

docker

Logs:

   Starting ccowd in foreground.
   Mar 03 23:31:00.162 edgefstest02.example.com ccowd[67] notice  [67]         util.c:654  : SERVERID: 90BC6597E47D9C7BEBA8C06281AF75E7 suffix=
   Mar 03 23:31:00.176 edgefstest02.example.com ccowd[67] notice  [69]  reptrans-rd.c:12248 : Local data store scsi-36000c296409ab1571c3e5026afdb1e66 kdev=/dev/sdb initialized
   Mar 03 23:31:00.176 edgefstest02.example.com ccowd[67] notice  [69]  reptrans-rd.c:12248 : Local data store scsi-36000c29883288cebbc302d9d27708fa5 kdev=/dev/sdc initialized
   Mar 03 23:31:00.176 edgefstest02.example.com ccowd[67] notice  [69]  reptrans-rd.c:12248 : Local data store scsi-36000c2904c07908d03d8634a9a5dc456 kdev=/dev/sdd initialized
   Mar 03 23:31:00.190 edgefstest02.example.com ccowd[67] notice  [69]  reptrans-rd.c:12313 : rdhold: /opt/nedge/sbin/rdhold, started successfully
   Mar 03 23:36:02.385 edgefstest02.example.com ccowd[67] error   [250]  reptrans-rd.c:10923 : Partition /dev/disk/by-id/scsi-36000c29883288cebbc302d9d27708fa5-part1 not found after 5 min polling
   Mar 03 23:36:02.390 edgefstest02.example.com ccowd[67] error   [300]  reptrans-rd.c:10923 : Partition /dev/disk/by-id/scsi-36000c2904c07908d03d8634a9a5dc456-part1 not found after 5 min polling
   Mar 03 23:36:02.401 edgefstest02.example.com ccowd[67] error   [195]  reptrans-rd.c:10923 : Partition /dev/disk/by-id/scsi-36000c296409ab1571c3e5026afdb1e66-part1 not found after 5 min polling
   Mar 03 23:36:02.401 edgefstest02.example.com ccowd[67] error   [69]     reptrans.c:6828 : Dev(scsi-36000c296409ab1571c3e5026afdb1e66) unable to open VDEV: -13
   Mar 03 23:36:02.401 edgefstest02.example.com ccowd[67] error   [69]     reptrans.c:6828 : Dev(scsi-36000c29883288cebbc302d9d27708fa5) unable to open VDEV: -13
   Mar 03 23:36:02.401 edgefstest02.example.com ccowd[67] error   [69]     reptrans.c:6828 : Dev(scsi-36000c2904c07908d03d8634a9a5dc456) unable to open VDEV: -13
   Mar 03 23:36:02.406 edgefstest02.example.com ccowd[67] notice  [69]     clengine.c:1344 : Cluster Engine join cluster: <corosync> node:<90BC6597E47D9C7BEBA8C06281AF75E7> ip:<::ffff:ffff:b15a:c0a> 4over6:1
   Mar 03 23:36:02.406 edgefstest02.example.com ccowd[67] notice  [69]     clengine.c:315  : hostcount changed from 0 to 1 
   Mar 03 23:36:02.409 edgefstest02.example.com ccowd[67] notice  [69]     clengine.c:334  : ringid changed from 0 to 13
   Mar 03 23:36:05.520 edgefstest02.example.com ccowd[67] error   [69]     flexhash.c:968  : Invalid value for table initialization: numdevices=0
   Mar 03 23:36:05.520 edgefstest02.example.com ccowd[67] error   [69]     flexhash.c:3894 : Error creating flexhash table 
   Mar 03 23:36:05.520 edgefstest02.example.com ccowd[67] error   [69]     clengine.c:1268 : Unable to read the flexhash table from corosync buffer
   Mar 03 23:36:05.521 edgefstest02.example.com ccowd[67] notice  [69]     clengine.c:1031 : Received new FlexHash update genid=1583278565544317
   Mar 03 23:36:07.408 edgefstest02.example.com ccowd[67] notice  [69]     clengine.c:315  : hostcount changed from 1 to 3 
   Mar 03 23:36:09.006 edgefstest02.example.com ccowd[67] error   [69]     flexhash.c:968  : Invalid value for table initialization: numdevices=0
   Mar 03 23:36:09.006 edgefstest02.example.com ccowd[67] error   [69]     flexhash.c:3894 : Error creating flexhash table 
   Mar 03 23:36:09.006 edgefstest02.example.com ccowd[67] error   [69]     clengine.c:1268 : Unable to read the flexhash table from corosync buffer
   Mar 03 23:36:09.007 edgefstest02.example.com ccowd[67] notice  [69]     clengine.c:1031 : Received new FlexHash update genid=1583278569030968
   Mar 03 23:36:09.426 edgefstest02.example.com ccowd[67] notice  [69]     clengine.c:1041 : Received a vdev dead message for 3A69D1F5ADEB81FACF97750175A2C8AD
   Mar 03 23:36:09.426 edgefstest02.example.com ccowd[67] notice  [69]     flexhash.c:3030 : VDEV 3A69D1F5ADEB81FACF97750175A2C8AD is leaving the Flexhash
   Mar 03 23:36:09.426 edgefstest02.example.com ccowd[67] notice  [69]     flexhash.c:2649 : Marking vdev: 3A69D1F5ADEB81FACF97750175A2C8AD as DEAD 
   Mar 03 23:36:09.428 edgefstest02.example.com ccowd[67] notice  [69]     clengine.c:1041 : Received a vdev dead message for 06D171D61366E5B8333225D90BC4902A
   Mar 03 23:36:09.428 edgefstest02.example.com ccowd[67] notice  [69]     flexhash.c:3030 : VDEV 06D171D61366E5B8333225D90BC4902A is leaving the Flexhash
   Mar 03 23:36:09.428 edgefstest02.example.com ccowd[67] notice  [69]     flexhash.c:2649 : Marking vdev: 06D171D61366E5B8333225D90BC4902A as DEAD 
   Mar 03 23:36:09.430 edgefstest02.example.com ccowd[67] notice  [69]     clengine.c:1041 : Received a vdev dead message for FE2E717BE4CA9F12B41ABDB0F2062566
   Mar 03 23:36:09.430 edgefstest02.example.com ccowd[67] notice  [69]     flexhash.c:3030 : VDEV FE2E717BE4CA9F12B41ABDB0F2062566 is leaving the Flexhash
   Mar 03 23:36:09.430 edgefstest02.example.com ccowd[67] notice  [69]     flexhash.c:2649 : Marking vdev: FE2E717BE4CA9F12B41ABDB0F2062566 as DEAD 

These logs are identical on each node,  and in vmware diskUUID=true is set on each node.

**Comment by dyusupov** [comment]
i recommend clean the disks exactly in this order: wipefs -a, dd zero, sgdisk -Z. The order is important because sgdisk has to be at the end....

**Comment by treyormsbee-interop** [comment]
That worked perfectly,  Ill pull thee wiki and add some of that info this week and do a pull request.

Thanks!

**Comment by dyusupov** [comment]
Great. Closing the issue.
