### ISSUE TITLE
Replicated NFS mount shows different stats for 'df' command

### ISSUE THREAD

**Issue by bosher** [Nexenta/edgefs#521]
### Steps to reproduce the behavior
Setup two clusters replication for nfs. Write some files on one end. Compare results of 'df' command. 

### Deployment type

- [ ] Kubernetes with Rook Operator
- [ ] Docker Compose

- [ ] Embedded with less than 8GB per EdgeFS Target or Daemon container
- [ ] Optimal resource allocation with more then 4 CPU and 8GB per EdgeFS Target or Daemon container

### Kubernetes cluster

- [ ] RedHat 7.x
- [ ] Ubuntu 16.04.x
- [ ] Ubuntu 18.04.x
- [ ] Other

**Comment by dyusupov** [comment]
integrated
